name: Python CI

# Dispara em push e pull request nas branches main e master
on:
  push:
    branches: [ main, teste-matheus ]
  pull_request:
    branches: [ main, teste-matheus ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          # Faz o lint em todo o código
          flake8 .

      - name: Run tests
        run: |
          pip install pytest
          pytest --maxfail=1 --disable-warnings -q
